import pygame as pg
import json
import sys
import os
import math
import time

WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT = 960, 480
DISPLAY_SIZE = DISPLAY_WIDTH, DISPLAY_HEIGHT = 512, 384

DIS_RATIO = min(WINDOW_WIDTH / DISPLAY_WIDTH, WINDOW_HEIGHT / DISPLAY_HEIGHT)

FLAGS = pg.RESIZABLE

FULL_SCREEN = False

TILE_SIZE = 16

FPS = 60

MOUSE_VISIBLE = False